import csv

# List of 200 tweet-sized messages
tweets = [
    "Excited to see what's next for $AAPL in the tech space.",
"$AAPL's stock performance reflects its solid fundamentals.",
"Wondering how $AAPL will capitalize on the latest trends in consumer tech.",
"$AAPL's innovation engine never ceases to amaze.",
"Anticipating the impact of $AAPL's upcoming product releases.",
"Keeping a close eye on $AAPL's market position amidst industry shifts.",
"Investors are bullish on $AAPL's long-term growth potential.",
"$AAPL's ecosystem continues to drive customer loyalty.",
"The competition struggles to keep up with $AAPL's pace of innovation.",
"$AAPL's brand remains synonymous with quality and innovation.",
"Analysts raise price targets for $AAPL amid strong demand.",
"Will $AAPL's next product launch break new ground?",
"Tech enthusiasts eagerly await $AAPL's next big announcement.",
"$AAPL's commitment to user privacy sets it apart from competitors.",
"Investors see $AAPL as a safe haven in turbulent times.",
"Rumors swirl about $AAPL's entry into new product categories.",
"$AAPL's product launches are always a global event.",
"Will $AAPL's new initiatives drive revenue growth?",
"Keeping an eye on $AAPL's market share in key regions.",
"Apple's innovation pipeline remains robust.",
"The iPhone continues to be the flagship product for $AAPL.",
"Investors applaud $AAPL's focus on sustainability.",
"Apple's services segment is a key driver of growth.",
"$AAPL's cash reserves provide a solid foundation for future investments.",
"The Apple Watch is gaining traction among fitness enthusiasts.",
"Will $AAPL's next acquisition shake up the industry?",
"Analysts predict strong iPhone sales for $AAPL this quarter.",
"$AAPL's commitment to diversity and inclusion is commendable.",
"Investors remain optimistic about $AAPL's long-term outlook.",
"The iPad Pro launch is a testament to $AAPL's innovation.",
"Tech analysts debate $AAPL's role in the future of mobility.",
"Apple's commitment to reducing its carbon footprint is laudable.",
"The success of AirPods highlights $AAPL's ability to innovate in accessories.",
"$AAPL's retail stores continue to be a destination for consumers.",
"Anticipating the impact of $AAPL's entry into the electric vehicle market.",
"Investors weigh the potential of $AAPL's healthcare initiatives.",
"$AAPL's commitment to user experience sets it apart in the smartphone market.",
"Will $AAPL's next software update drive iPhone upgrades?",
"The Apple Card is gaining traction among consumers.",
"Investors expect strong earnings from $AAPL this quarter.",
"$AAPL's investment in AR technology could revolutionize the industry.",
"The Mac lineup remains a bright spot for $AAPL.",
"Apple's commitment to privacy and security resonates with consumers.",
"Investors analyze $AAPL's supply chain resilience.",
"The success of Apple Music underscores $AAPL's diversification strategy.",
"$AAPL's commitment to renewable energy is commendable.",
"Investors anticipate the impact of $AAPL's upcoming dividend announcement.",
"The Apple Watch Series 7 launch is highly anticipated.",
"$AAPL's commitment to reducing e-waste is a step in the right direction.",
"Investors speculate about $AAPL's next big acquisition target.",
"The iPhone SE continues to be a popular choice for budget-conscious consumers.",
"Will $AAPL's investment in original content pay off?",
"The success of Apple Arcade highlights $AAPL's ability to innovate in gaming.",
"Investors see $AAPL as a leader in the smart home market.",
"Tech analysts debate the future of wearables and $AAPL's role.",
"The Apple Car project could be a game-changer for $AAPL.",
"Investors analyze the potential impact of $AAPL's streaming service.",
"Apple's commitment to accessibility features is commendable.",
"$AAPL's expansion into financial services is gaining momentum.",
"The success of Apple Podcasts highlights $AAPL's ability to diversify revenue streams.",
"Investors applaud $AAPL's commitment to employee well-being.",
"The Apple Watch Series 8 launch is expected to set new standards.",
"$AAPL's investment in augmented reality technology is generating excitement.",
"Investors remain bullish on $AAPL despite market volatility.",
"The success of Apple Fitness+ underscores $AAPL's ability to innovate in fitness tech.",
"$AAPL's commitment to reducing its carbon footprint is gaining attention.",
"Investors speculate about $AAPL's role in the future of autonomous vehicles.",
"The iPhone 14 launch is expected to drive strong demand.",
"$AAPL's expansion into healthcare technology is gaining traction.",
"Apple's commitment to environmental sustainability sets it apart from competitors.",
"Investors anticipate strong demand for the iPhone 13 lineup.",
"The Apple Watch Series 9 launch is highly anticipated.",
"$AAPL's investment in electric vehicle technology is generating excitement.",
"Investors analyze the impact of $AAPL's recent acquisitions.",
"The success of Apple TV+ highlights $AAPL's ability to compete in streaming.",
"$AAPL's commitment to reducing its reliance on third-party suppliers is paying off.",
"Investors speculate about $AAPL's entry into the metaverse.",
"The iPhone 15 launch is expected to be a major catalyst for $AAPL's stock.",
"$AAPL's expansion into financial services is positioning it as a fintech leader.",
"The success of Apple Podcasts highlights $AAPL's ability to diversify revenue streams.",
"Investors are bullish on $AAPL's long-term growth prospects.",
"The Apple Watch Series 10 launch is expected to set new benchmarks.",
"$AAPL's investment in AR glasses could transform the way we interact with technology.",
"Investors applaud $AAPL's commitment to reducing electronic waste.",
"The success of Apple Music underscores $AAPL's ability to compete in the music streaming market.",
"$AAPL's expansion into autonomous vehicles is generating excitement among investors.",
"Investors remain optimistic about $AAPL's future growth trajectory.",
"The iPhone 16 launch is expected to drive strong sales.",
"$AAPL's expansion into healthcare technology is poised to disrupt the industry.",
"Apple's commitment to accessibility features is commendable.",
"Investors speculate about $AAPL's next big move in the gaming industry.",
"The Apple Watch Series 11 launch is highly anticipated.",
"$AAPL's investment in virtual reality technology could open new revenue streams.",
"Investors remain bullish on $AAPL despite regulatory scrutiny.",
"The success of Apple Fitness+ highlights $AAPL's ability to innovate in the fitness market.",
"$AAPL's commitment to reducing its environmental impact is gaining attention.",
"Investors are excited about $AAPL's expansion into augmented reality.",
"The iPhone 17 launch is expected to drive strong demand.",
"$AAPL's expansion into financial services is gaining momentum.",
"The success of Apple Podcasts highlights $AAPL's ability to diversify revenue streams.",
"Investors applaud $AAPL's commitment to employee well-being.",
"The Apple Watch Series 12 launch is highly anticipated.",
"$AAPL's investment in electric vehicle technology is generating excitement.",
"Investors analyze the impact of $AAPL's recent acquisitions.",
"The success of Apple TV+ underscores $AAPL's ability to compete in streaming.",
"$AAPL's commitment to reducing its reliance on third-party suppliers is paying off.",
"Investors speculate about $AAPL's entry into the metaverse.",
"The iPhone 15 launch is expected to be a major catalyst for $AAPL's stock.",
"$AAPL's expansion into financial services is positioning it as a fintech leader.",
"The success of Apple Podcasts highlights $AAPL's ability to diversify revenue streams.",
"Investors are bullish on $AAPL's long-term growth prospects.",
"The Apple Watch Series 10 launch is expected to set new benchmarks.",
"$AAPL's investment in AR glasses could transform the way we interact with technology.",
"Investors applaud $AAPL's commitment to reducing electronic waste.",
"The success of Apple Music underscores $AAPL's ability to compete in the music streaming market.",
"$AAPL's expansion into autonomous vehicles is generating excitement among investors.",
"Investors remain optimistic about $AAPL's future growth trajectory.",
"The iPhone 16 launch is expected to drive strong sales.",
"$AAPL's expansion into healthcare technology is poised to disrupt the industry.",
"Apple's commitment to accessibility features is commendable.",
"Investors speculate about $AAPL's next big move in the gaming industry.",
"The Apple Watch Series 11 launch is highly anticipated.",
"$AAPL's investment in virtual reality technology could open new revenue streams.",
"Investors remain bullish on $AAPL despite regulatory scrutiny.",
"The success of Apple Fitness+ highlights $AAPL's ability to innovate in the fitness market.",
"$AAPL's commitment to reducing its environmental impact is gaining attention.",
"Investors are excited about $AAPL's expansion into augmented reality.",
"The iPhone 17 launch is expected to drive strong demand.",
"$AAPL's expansion into financial services is gaining momentum.",
"The success of Apple Podcasts highlights $AAPL's ability to diversify revenue streams.",
"Investors applaud $AAPL's commitment to employee well-being.",
"The Apple Watch Series 12 launch is highly anticipated.",
"$AAPL's investment in electric vehicle technology is generating excitement.",
"Investors analyze the impact of $AAPL's recent acquisitions.",
"The success of Apple TV+ underscores $AAPL's ability to compete in streaming.",
"$AAPL's commitment to reducing its reliance on third-party suppliers is paying off.",
"Investors speculate about $AAPL's entry into the metaverse.",
"The iPhone 15 launch is expected to be a major catalyst for $AAPL's stock.",
"$AAPL's expansion into financial services is positioning it as a fintech leader.",
"The success of Apple Podcasts highlights $AAPL's ability to diversify revenue streams.",
"Investors are bullish on $AAPL's long-term growth prospects.",
"The Apple Watch Series 10 launch is expected to set new benchmarks.",
"$AAPL's investment in AR glasses could transform the way we interact with technology.",
"Investors applaud $AAPL's commitment to reducing electronic waste.",
"The success of Apple Music underscores $AAPL's ability to compete in the music streaming market.",
"$AAPL's expansion into autonomous vehicles is generating excitement among investors.",
"Investors remain optimistic about $AAPL's future growth trajectory.",
"The iPhone 16 launch is expected to drive strong sales.",
"$AAPL's expansion into healthcare technology is poised to disrupt the industry.",
"Apple's commitment to accessibility features is commendable.",
"Investors speculate about $AAPL's next big move in the gaming industry.",
"The Apple Watch Series 11 launch is highly anticipated.",
"$AAPL's investment in virtual reality technology could open new revenue streams.",
"Investors remain bullish on $AAPL despite regulatory scrutiny.",
"The success of Apple Fitness+ highlights $AAPL's ability to innovate in the fitness market.",
"$AAPL's commitment to reducing its environmental impact is gaining attention.",
"Investors are excited about $AAPL's expansion into augmented reality.",
"The iPhone 17 launch is expected to drive strong demand.",
"$AAPL's expansion into financial services is gaining momentum.",
"The success of Apple Podcasts highlights $AAPL's ability to diversify revenue streams.",
"Investors applaud $AAPL's commitment to employee well-being.",
"The Apple Watch Series 12 launch is highly anticipated.",
"$AAPL's investment in electric vehicle technology is generating excitement.",
"Investors analyze the impact of $AAPL's recent acquisitions.",
"The success of Apple TV+ underscores $AAPL's ability to compete in streaming.",
"$AAPL's commitment to reducing its reliance on third-party suppliers is paying off.",
"Investors speculate about $AAPL's entry into the metaverse.",
"The iPhone 15 launch is expected to be a major catalyst for $AAPL's stock.",
"$AAPL's expansion into financial services is positioning it as a fintech leader.",
"The success of Apple Podcasts highlights $AAPL's ability to diversify revenue streams.",
"Investors are bullish on $AAPL's long-term growth prospects.",
"The Apple Watch Series 10 launch is expected to set new benchmarks.",
"$AAPL's investment in AR glasses could transform the way we interact with technology.",
"Investors applaud $AAPL's commitment to reducing electronic waste.",
"The success of Apple Music underscores $AAPL's ability to compete in the music streaming market.",
"$AAPL's expansion into autonomous vehicles is generating excitement among investors.",
"Investors remain optimistic about $AAPL's future growth trajectory.",
"The iPhone 16 launch is expected to drive strong sales.",
"$AAPL's expansion into healthcare technology is poised to disrupt the industry.",
"Apple's commitment to accessibility features is commendable.",
"Investors speculate about $AAPL's next big move in the gaming industry.",
"The Apple Watch Series 11 launch is highly anticipated.",
"$AAPL's investment in virtual reality technology could open new revenue streams.",
"Investors remain bullish on $AAPL despite regulatory scrutiny.",
"The success of Apple Fitness+ highlights $AAPL's ability to innovate in the fitness market.",
"$AAPL's commitment to reducing its environmental impact is gaining attention.",
"Investors are excited about $AAPL's expansion into augmented reality.",
"The iPhone 17 launch is expected to drive strong demand."
]

# Define the CSV file path
csv_file = "tweets.csv"

# Write the tweets to the CSV file
with open(csv_file, 'w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(["Tweet"])  # Write the header
    for tweet in tweets:
        writer.writerow([tweet])

print("CSV file created successfully.")
